[[synonyms]]
meaning = "热切的、渴望的 adj."
words = ["eager", "ardent", "avid", "impassioned", "zealous", "keen"]

[[synonyms]]
meaning = "敏锐的 adj."
words = ["incisive", "astute", "perceptive", "shrewd", "discerning", "keen"]

[[synonyms]]
meaning = "讥讽、嘲笑 n."
words = ["mockery", "derision", "ridicule", "contempt", "sarcasm", "disdain", "insult", "jibe", "taunt", "satire"]

[[synonyms]]
meaning = "尖刻 n."
words = ["acrimony", "mordancy", "virulence", "bitterness", "sarcasm"]

[[synonyms]]
meaning = "分割、划分 v."
words = ["compartmentalize", "assort", "categorize", "classify"]

[[synonyms]]
meaning = "解雇、驱逐 v."
words = ["dismiss", "fire", "sack"]

[[synonyms]]
meaning = "拆除、废除 v."
words = ["dismantle", "annihilate", "demolish", "raze", "wreck", "ruin"]

[[synonyms]]
meaning = "健谈的 adj."
words = ["voluble", "garrulous", "glib", "loquacious", "talkative", "verbose"]

[[synonyms]]
meaning = "冗长的、罗嗦的 adj."
words = ["verbose", "diffuse", "loquacious", "prolix", "rambling", "garrulous"]

[[synonyms]]
meaning = "扩散、散布 v."
words = ["spread", "promulgate", "disperse", "disseminate", "diffuse"]

[[synonyms]]
meaning = "宣布、声明 v."
words = ["proclaim", "profess", "announce", "declare", "promulgate", "trumpet"]

[[synonyms]]
meaning = "迷住、入迷 v."
words = ["enamor", "enchant", "enthrall", "fascinate", "bewitch", "captivate"]

[[synonyms]]
meaning = "抑制、削弱 v."
words = ["dampen", "check", "inhibit", "lessen", "stifle", "suppress"]

[[synonyms]]
meaning = "狂热的，热情的 adj."
words = ["zealous", "impassioned", "fervent", "fiery", "passionate", "enthusiastic"]

[[synonyms]]
meaning = "赞美、赞颂 n."
words = ["tribute", "compliment", "eulogy", "panegyric", "paean", "encomium"]

[[synonyms]]
meaning = "基本原理、基础 n."
words = ["rationale", "argument", "principle", "hypothesis", "grounds"]

[[synonyms]]
meaning = "不情愿的、勉强的 adj."
words = ["reluctant", "loath", "averse", "disinclined", "indisposed", "unwilling"]

[[synonyms]]
meaning = "大杂烩、混合物 n."
words = ["hodgepodge", "patchwork", "mixture", "pastiche", "welter", "assortment", "collage", "medley"]

[[synonyms]]
meaning = "微小的、极小的 adj."
words = ["diminutive", "minuscule", "tiny", "minute", "microscopic", "infinitesimal"]

[[synonyms]]
meaning = "观察、观测 n."
words = ["scrutiny", "examination", "inspection", "scrutinization", "observation", "watching"]

[[synonyms]]
meaning = "压迫的、残酷的 adj."
words = ["oppressive", "brutal", "inhuman", "harsh", "despotic", "tyrannical", "cruel"]

[[synonyms]]
meaning = "全面、彻底的 adj."
words = ["exhaustive", "encyclopedic", "comprehensive", "thorough", "all-encompassing", "sweeping", "all-embracing", "complete"]

[[synonyms]]
meaning = "完全的、彻底的 adj."
words = ["downright", "thorough", "utter", "absolute", "outright", "categorical"]

[[synonyms]]
meaning = "纯粹的 adj."
words = ["pure", "fine", "refined", "neat", "plain", "absolute", "unqualified", "purified", "unalloyed"]

[[synonyms]]
meaning = "混乱、杂乱 n."
words = ["hodgepodge", "pandemonium", "turmoil", "muddle", "mess", "jumble", "chaos", "welter"]

[[synonyms]]
meaning = "断言、坚称 v."
words = ["assert", "aver", "allege", "avow", "avouch", "insist"]

[[synonyms]]
meaning = "言简意赅的 adj."
words = ["laconic", "terse", "taciturn", "curt", "reticent", "reserved", "succinct"]

[[synonyms]]
meaning = "卑劣的 adj."
words = ["sleazy", "sordid", "shameful", "seamy", "seedy"]

[[synonyms]]
meaning = "玷污、败坏 adj."
words = ["taint", "blemish", "spoil", "tarnish", "corrupt", "defile", "stain", "contaminate"]

[[synonyms]]
meaning = "优点、长处 n."
words = ["virtue", "distinction", "exellency", "grace", "merit", "value", "exellence"]

[[synonyms]]
meaning = "美德 n."
words = ["virtue", "character", "decency", "goodness", "honesty", "integrity", "probity"]

[[synonyms]]
meaning = "大胆的、放肆的 adj."
words = ["audacious", "impudent", "unflinching", "presumptuous", "valiant", "intrepid"]

[[synonyms]]
meaning = "强制、强迫 v."
words = ["constrain", "compel", "urge", "force", "coerce", "press"]

[[synonyms]]
meaning = "限制、限定 v."
words = ["constrain", "restrict", "restrain", "inhibit", "curb", "check", "limit"]

[[synonyms]]
meaning = "先入之见、成见 n."
words = ["preconception", "prejudgement", "prepossession"]

[[synonyms]]
meaning = "无处不在的 adj."
words = ["omnipresent", "ubiquitous", "universal"]

[[synonyms]]
meaning = "对立（面） n."
words = ["antithesis", "opposite", "opposition", "contrast", "contrary"]

[[synonyms]]
meaning = "兴旺 v."
words = ["prosper", "thrive", "flourish", "bloom"]

[[synonyms]]
meaning = "实用主义的 adj."
words = ["utilitarian", "functional", "practical", "useful"]

[[synonyms]]
meaning = "不稳定、不可预测的 adj."
words = ["unpredictable", "erratic", "volatile", "capricious", "fickle", "mercurial"]

[[synonyms]]
meaning = "古怪的 adj."
words = ["bizarre", "erratic", "eccentric", "fantastic", "whimsical", "outlandish", "weird", "quirky"]

[[synonyms]]
meaning = "极端分子 n."
words = ["extremist", "zealot"]

[[synonyms]]
meaning = "摇摆 v."
words = ["vacillate", "sway", "vibrate", "waver", "fluctuate", "oscillate"]

[[synonyms]]
meaning = "犹豫 v."
words = ["vacillate", "hesitate", "waver", "dither", "falter", "oscillate"]

[[synonyms]]
meaning = "犹豫不决、优柔寡断 n."
words = ["irresolution", "vacillation", "hesitancy", "indecision", "wavering", "ambivalence"]

[[synonyms]]
meaning = "冲动的、任性的 adj."
words = ["capricious", "impulsive", "reckless", "hasty", "rash", "impetuous"]

[[synonyms]]
meaning = "快速派遣 v."
words = ["dispatch", "send", "transmit", "consign", "mail"]
 
[[synonyms]]
meaning = "迅速 n."
words = ["dispatch", "swiftness", "celerity", "promptness", "rapidity", "briskness"]

[[synonyms]]
meaning = "有洞察力的 adj."
words = ["perspicacious", "astute", "shrewd", "discernible", "discerning", "perceptive"]

[[synonyms]]
meaning = "察觉、辨识 v."
words = ["discern", "detect", "discriminate", "perceive", "recognize", "distinguish"]

[[synonyms]]
meaning = "精明的 adj."
words = ["anny", "astute", "acute", "shrewd", "prudent", "judicious"]

[[synonyms]]
meaning = "灵巧的、精明的 adj."
words = ["cunning", "shrewd", "crafty", "ingenious", "astute", "canny"]

[[synonyms]]
meaning = "熟练、灵巧的 adj."
words = ["dexterous", "deft", "canny", "proficient", "agile", "adroit", "adept"]

[[synonyms]]
meaning = "狡猾的 adj."
words = ["cunning", "wily", "crafty", "slippery", "artful", "devious"]

[[synonyms]]
meaning = "误解、曲解 v."
words = ["misconstrue", "garble", "misunderstand", "misapprehend", "misinterpret", "distort"]

[[synonyms]]
meaning = "预示、预兆 v."
words = ["presage", "portend", "adumbrate", "augur", "forebode", "herald", "betoken", "signify"]

[[synonyms]]
meaning = "预知的 adj."
words = ["prescient", "prophetic", "farsighted", "foreseeing", "prognostic", "predictive"]

[[synonyms]]
meaning = "聚集 v."
words = ["cluster", "collect", "aggregate", "assemble", "accumulate"]

[[synonyms]]
meaning = "（供应）过剩 n."
words = ["glut", "surfeit", "surplus", "excess", "plethora"]

[[synonyms]]
meaning = "短暂的、片刻的 adj."
words = ["momentary", "transient", "fleeting", "ephemeral", "evanescent", "transitory"]

[[synonyms]]
meaning = "划定界限 v."
words = ["demarcate", "delimit", "mark", "delineate"]

[[synonyms]]
meaning = "博学的 adj."
words = ["erudite", "polymath", "intelligent", "intellectual", "well-informed", "learned"]

[[synonyms]]
meaning = "尖叫 v."
words = ["shriek", "cry", "caterwaul", "scream", "yell", "screech", "roar"]

[[synonyms]]
meaning = "忽略 v."
words = ["overlook", "ignore", "neglect"]

[[synonyms]]
meaning = "奇异的、令人惊叹的 adj."
words = ["wondrous", "marvelous", "fantastic", "amazing", "wonderful", "astonishing"]

[[synonyms]]
meaning = "引起敌意 v."
words = ["irritate", "vex", "rile", "offend", "provoke", "antagonize"]

[[synonyms]]
meaning = "惊恐、焦虑不安 n."
words = ["trepidation", "misconcertment", "misgiving", "apprehension", "agitation", "unease"]

[[synonyms]]
meaning = "使慌乱不安 v."
words = ["unnerve", "fluster", "perturb", "disconcert", "disturb", "rattle"]

[[synonyms]]
meaning = "多用途的 adj."
words = ["versatile", "protean", "universal", "adaptable", "multifunctional"]

[[synonyms]]
meaning = "低下的、卑微的 adj."
words = ["unpretentious", "lowly", "humble", "modest", "unassuming"]

[[synonyms]]
meaning = "搁置、中止 n."
words = ["quiescence", "abeyance", "suspension", "moratorium", "doldrums", "adjournment"]

[[synonyms]]
meaning = "多产的、丰富的 adj."
words = ["prolific", "productive", "fecund", "abundant", "profuse", "copious"]

[[synonyms]]
meaning = "恰当的 adj."
words = ["felicitous", "apt", "appropriate", "apposite", "apropos", "fitting", "germane", "pertinent"]

[[synonyms]]
meaning = "感激的 adj."
words = ["indebted", "grateful", "obligated", "beholden", "obliged", "appreciative"]

[[synonyms]]
meaning = "证实 v."
words = ["corroborate", "confirm", "justify", "validate", "verify", "authenticate", "attest"]

[[synonyms]]
meaning = "一丝不苟的、小心谨慎的 adj."
words = ["meticulous", "painstaking", "thorough", "scrupulous", "careful", "conscientious", "punctilious"]
 
[[synonyms]]
meaning = "谨慎的、考虑周全的 adj."
words = ["considerate", "guarded", "tactful", "prudent", "circumspect", "discreet"]

[[synonyms]]
meaning = "仓促、匆忙的 adj."
words = ["cursory", "precipitate", "hasty", "headless"]

[[synonyms]]
meaning = "一贯正确的 adj."
words = ["unerring", "flawless", "impeccable", "faultless", "unfailing"]

[[synonyms]]
meaning = "鉴赏家 n."
words = ["connoisseur", "expert", "specialist", "pundit", "virtuoso"]

[[synonyms]]
meaning = "没有根据的 adj."
words = ["unfounded", "baseless", "untenable", "groundless", "unjustified"]

[[synonyms]]
meaning = "盛气凌人的 adj."
words = ["condescending", "arrogant", "supercilious", "patronizing", "snobbing", "haughty"]

[[synonyms]]
meaning = "扩展、详述 v."
words = ["amplify", "enlarge", "elaborate"]

[[synonyms]]
meaning = "增强、扩大 v."
words = ["amplify", "magnify", "intensify", "escalate", "augment", "boost"]

[[synonyms]]
meaning = "晦涩难懂的 adj."
words = ["obscure", "opaque", "impenetrable", "arcane", "unfathomable", "inscrutable"]

[[synonyms]]
meaning = "难以理解的 adj."
words = ["ambiguous", "opaque", "arcane", "cryptic", "equivocal", "inscrutable"]

[[synonyms]]
meaning = "鲜为人知的 adj."
words = ["anonymous", "nondescript", "commonplace", "mundane", "undistinguished", "obscure"]

[[synonyms]]
meaning = "平常无奇的 adj."
words = ["commonplace", "mundane", "pedestrian", "prosaic", "dull", "banal", "humdrum"]

[[synonyms]]
meaning = "陈词滥调 n."
words = ["banality", "cliche", "platitude", "commonplace", "truism", "triteness", "conventionality"]

[[synonyms]]
meaning = "艰巨的 adj."
words = ["onerous", "arduous", "burdensome", "grueling", "taxing"]

[[synonyms]]
meaning = "不透光的 adj."
words = ["opaque", "blurry", "dim", "murky", "obscure", "shadowy"]

[[synonyms]]
meaning = "缺乏的 adj."
words = ["sparse", "meager", "scarce", "scant", "limited", "insufficient", "deficient"]

[[synonyms]]
meaning = "过度的 adj."
words = ["excessive", "undue", "exorbitant", "overdue", "immoderate", "intemperate"]

[[synonyms]]
meaning = "怪癖 n."
words = ["quirk", "eccentricity", "oddity", "peculiarity", "idiosyncrasy"]

[[synonyms]]
meaning = "赚钱的 adj."
words = ["lucrative", "remunerative", "profitable", "rewarding"]

[[synonyms]]
meaning = "掩饰 v."
words = ["belie", "disguise", "conceal", "veil", "mask", "camouflage"]

[[synonyms]]
meaning = "拆穿、揭露为假 v."
words = ["debunk", "expose", "disprove", "belie", "invalidate", "controvert"]

[[synonyms]]
meaning = "缓和、减轻 v."
words = ["mitigate", "abate", "tempor", "allay", "alleviate", "mollify", "palliate", "soothe", "appease", "assuage", "pacify", "relieve", "ease"]

[[synonyms]]
meaning = "消除、使不必要 v."
words = ["obviate", "avert", "perclude", "prevent", "eliminate", "remove"]

[[synonyms]]
meaning = "认可、支持 v."
words = ["endorse", "uphold", "accredit", "advocate", "champion", "countenance"]

[[synonyms]]
meaning = "谴责 v."
words = ["condemn", "decry", "censure", "denounce", "execrate", "reprobate"]

[[synonyms]]
meaning = "相称的 adj."
words = ["commensurate", "proportionate", "comparable", "equivalent"]

[[synonyms]]
meaning = "可交换的 adj."
words = ["interchangeable", "fungible", "synonymous", "equivalent", "identical"]

[[synonyms]]
meaning = "可替代的 adj."
words = ["fungible", "interchangeable"]

[[synonyms]]
meaning = "歧视的 adj."
words = ["discriminatory", "prejudiced", "unfair", "biased"]

[[synonyms]]
meaning = "过时的 adj."
words = ["anachronistic", ", old-fashioned", "outmoded", "obsolete", "antiquated", "archaic", "antediluvian"]

[[synonyms]]
meaning = "纪实的 adj."
words = ["chronicled", "archived", "genuine", "factual", "documentary"]

[[synonyms]]
meaning = "国际性的、见多识广的 adj."
words = ["cosmopolitan", "global", "universal", "worldwide"]

[[synonyms]]
meaning = "反对、不同意 v."
words = ["dissent", "discord", "contradict", "demur", "object"]

[[synonyms]]
meaning = "友好、和睦 n."
words = ["harmony", "concord", "amity", "comity", "friendship"]

[[synonyms]]
meaning = "服从 v."
words = ["conform", "obey", "accord", "harmoize", "square"]

[[synonyms]]
meaning = "反复无常的、轻浮的 adj."
words = ["flighty", "frivolous", "flippant", "giddy"]

[[synonyms]]
meaning = "声明与...脱离关系 v."
words = ["abandon", "abjure", "disavow", "repudiate", "renounce", "disown"]

[[synonyms]]
meaning = "清晰可见的 adj."
words = ["tangible", "palpable", "perceptible", "concrete", "definite"]

[[synonyms]]
meaning = "疾病、弊端 n."
words = ["malady", "ailment", "illness", "disease", "sickness"]

[[synonyms]]
meaning = "折磨、困扰 v."
words = ["agonize", "beset", "besiege", "afflict", "barass", "pester", "plague"]

[[synonyms]]
meaning = "瘟疫、灾祸 n."
words = ["plague", "epidemic", "infestation", "pandemic", "scourge"]

[[synonyms]]
meaning = "接触传染的 adj."
words = ["contagious", "endemic", "infectious", "pandemic", "epidemic"]

[[synonyms]]
meaning = "解决方法 n."
words = ["panacea", "solution", "antidote", "curative", "rectifier", "therapy", "remedy"]

[[synonyms]]
meaning = "年老的 adj."
words = ["old", "senior", "advanced", "aged"]

[[synonyms]]
meaning = "棘手的、难以解决的 adj."
words = ["knotty", "complicated", "baffling", "thorny", "taxing", "troublesome"]

[[synonyms]]
meaning = "构成、形成 v."
words = ["constitute", "consist", "compose"]

[[synonyms]]
meaning = "乐观的 adj."
words = ["upbeat", "confident", "optimistic", "cheerful", "buoyant", "animated", "sanguin"]

[[synonyms]]
meaning = "权威的、威严的 adj."
words = ["authoritative", "magisterial"]

[[synonyms]]
meaning = "令人讨厌的 adj."
words = ["noisome", "disagreeable", "abominable", "abhorrent", "odious", "objectionable", "noxious"]

[[synonyms]]
meaning = "恶臭的 adj."
words = ["noisome", "fetid", "foul", "malodorous", "stinking", "smelly"]

[[synonyms]]
meaning = "镇定的、沉着的 adj."
words = ["composed", "unperturbed", "collected", "calm", "imperturbed", "unflappable", "serene", "sedate"]

[[synonyms]]
meaning = "持久的、耐用的 adj."
words = ["durable", "constant", "enduring", "permanent", "persistent", "everlasting"]

[[synonyms]]
meaning = "过度吹捧 n."
words = ["adulation", "sycophancy", "flattery", "fawning", "praise", "compliment"]

[[synonyms]]
meaning = "惹眼的 adj."
words = ["noticeable", "protruding", "conspicuous", "obstrusive"]

[[synonyms]]
meaning = "清晰表达 v."
words = ["enunciate", "proclaim", "reveal", "assert", "utter", "articulate"]

[[synonyms]]
meaning = "表达清晰的 adj."
words = ["intelligible", "lucid", "illuminating", "comprehensible", "articulate"]

[[synonyms]]
meaning = "狂喜 n."
words = ["ecstasy", "elation", "rapture", "delight", "bliss", "exhilaration", "euphoria"]

[[synonyms]]
meaning = "分阶层的 adj."
words = ["stratified", "hierarchical", "ranked", "graded"]

[[synonyms]]
meaning = "警告、责备 v."
words = ["admonish", "rebuke", "chide", "reprove", "reprimand", "scold"]

[[synonyms]]
meaning = "忠告、劝告 v."
words = ["admonish", "advise", "recommend", "urge", "consel"]
