[[synonyms]]
meaning = "热切的、渴望的 adj."
words = ["eager", "ardent", "avid", "impassioned", "zealous", "keen"]

[[synonyms]]
meaning = "敏锐的 adj."
words = ["incisive", "astute", "perceptive", "shrewd", "discerning", "keen"]

[[synonyms]]
meaning = "嘲笑 n."
words = ["mockery", "derision", "ridicule", "contempt", "sarcasm", "disdain", "insult"]

[[synonyms]]
meaning = "分割、划分 v."
words = ["compartmentalize", "assort", "categorize", "classify"]

[[synonyms]]
meaning = "解雇、驱逐 v."
words = ["dismiss", "fire", "sack"]

[[synonyms]]
meaning = "拆除、废除 v."
words = ["dismantle", "annihilate", "demolish", "raze", "wreck", "ruin"]

[[synonyms]]
meaning = "健谈的 adj."
words = ["voluble", "garrulous", "glib", "loquacious", "talkative", "verbose"]

[[synonyms]]
meaning = "迷住、入迷 v."
words = ["enamor", "enchant", "enthrall", "fascinate", "bewitch", "captivate"]

[[synonyms]]
meaning = "抑制、削弱 v."
words = ["dampen", "check", "inhibit", "lessen", "stifle", "suppress"]

[[synonyms]]
meaning = "狂热的，热情的 adj."
words = ["zealous", "impassioned", "fervent", "fiery", "passionate", "enthusiastic"]

[[synonyms]]
meaning = "赞美、赞颂 n."
words = ["tribute", "compliment", "eulogy", "panegyric", "paean", "encomium"]

[[synonyms]]
meaning = "基本原理、基础 n."
words = ["rationale", "argument", "principle", "hypothesis", "grounds"]

[[synonyms]]
meaning = "不情愿的、勉强的 adj."
words = ["reluctant", "loath", "averse", "disinclined", "indisposed", "unwilling"]

[[synonyms]]
meaning = "大杂烩、混合物 n."
words = ["hodgepodge", "patchwork", "mixture", "pastiche", "welter", "assortment", "collage", "medley"]

[[synonyms]]
meaning = "微小的、极小的 adj."
words = ["diminutive", "minuscule", "tiny", "minute", "microscopic", "infinitesimal"]

[[synonyms]]
meaning = "观察、观测 n."
words = ["scrutiny", "examination", "inspection", "scrutinization", "observation", "watching"]

[[synonyms]]
meaning = "压迫的、残酷的 adj."
words = ["oppressive", "brutal", "inhuman", "harsh", "despotic", "tyrannical", "cruel"]

[[synonyms]]
meaning = "全面、彻底的 adj."
words = ["exhaustive", "encyclopedic", "comprehensive", "thorough", "all-encompassing", "sweeping", "all-embracing", "complete"]

[[synonyms]]
meaning = "混乱、杂乱 n."
words = ["hodgepodge", "pandemonium", "turmoil", "muddle", "mess", "jumble", "chaos", "welter"]

[[synonyms]]
meaning = "断言、坚称 v."
words = ["assert", "aver", "allege", "avow", "avouch", "insist"]

[[synonyms]]
meaning = "言简意赅的 adj."
words = ["laconic", "terse", "taciturn", "curt", "reticent", "reserved", "succinct"]

[[synonyms]]
meaning = "卑劣的 adj."
words = ["sleazy", "sordid", "shameful", "seamy", "seedy"]

[[synonyms]]
meaning = "玷污、败坏 adj."
words = ["taint", "blemish", "spoil", "tarnish", "corrupt", "defile", "stain", "contaminate"]

[[synonyms]]
meaning = "优点、长处 n."
words = ["virtue", "distinction", "exellency", "grace", "merit", "value", "exellence"]

[[synonyms]]
meaning = "美德 n."
words = ["virtue", "character", "decency", "goodness", "honesty", "integrity", "probity"]

[[synonyms]]
meaning = "大胆的、放肆的 adj."
words = ["audacious", "impudent", "unflinching", "presumptuous", "valiant", "intrepid"]

[[synonyms]]
meaning = "强制、强迫 v."
words = ["constrain", "compel", "urge", "force", "coerce", "press"]

[[synonyms]]
meaning = "限制、限定 v."
words = ["constrain", "restrict", "restrain", "inhibit", "curb", "check", "limit"]

[[synonyms]]
meaning = "先入之见、成见 n."
words = ["preconception", "prejudgement", "prepossession"]

[[synonyms]]
meaning = "无处不在的 adj."
words = ["omnipresent", "ubiquitous", "universal"]

[[synonyms]]
meaning = "对立（面） n."
words = ["antithesis", "opposite", "opposition", "contrast", "contrary"]

[[synonyms]]
meaning = "兴旺 v."
words = ["prosper", "thrive", "flourish", "bloom"]

[[synonyms]]
meaning = "实用主义的 adj."
words = ["utilitarian", "functional", "practical", "useful"]

[[synonyms]]
meaning = "不稳定、不可预测的 adj."
words = ["unpredictable", "erratic", "volatile", "capricious", "fickle", "mercurial"]

[[synonyms]]
meaning = "古怪的 adj."
words = ["bizarre", "erratic", "eccentric", "fantastic", "whimsical", "outlandish", "weird"]

[[synonyms]]
meaning = "极端分子 n."
words = ["extremist", "zealot"]

[[synonyms]]
meaning = "摇摆 v."
words = ["vacillate", "sway", "vibrate", "waver", "fluctuate", "oscillate"]

[[synonyms]]
meaning = "犹豫 v."
words = ["vacillate", "hesitate", "waver", "dither", "falter", "oscillate"]

[[synonyms]]
meaning = "犹豫不决、优柔寡断 n."
words = ["irresolution", "vacillation", "hesitancy", "indecision", "wavering", "ambivalence"]

[[synonyms]]
meaning = "冲动的、任性的 adj."
words = ["capricious", "impulsive", "reckless", "hasty", "rash", "impetuous"]

[[synonyms]]
meaning = "快速派遣 v."
words = ["dispatch", "send", "transmit", "consign", "mail"]
 
[[synonyms]]
meaning = "迅速 n."
words = ["dispatch", "swiftness", "celerity", "promptness", "rapidity", "briskness"]

[[synonyms]]
meaning = "有洞察力的 adj."
words = ["perspicacious", "astute", "shrewd", "discernible", "discerning", "perceptive"]

[[synonyms]]
meaning = "精明的 adj."
words = ["anny", "astute", "acute", "shrewd", "prudent", "judicious"]

[[synonyms]]
meaning = "灵巧的、精明的 adj."
words = ["cunning", "shrewd", "crafty", "ingenious", "astute", "canny"]

[[synonyms]]
meaning = "熟练、灵巧的 adj."
words = ["dexterous", "deft", "canny", "proficient", "agile", "adroit", "adept"]

[[synonyms]]
meaning = "狡猾的 adj."
words = ["cunning", "wily", "crafty", "slippery", "artful", "devious"]

[[synonyms]]
meaning = "误解、曲解 v."
words = ["misconstrue", "garble", "misunderstand", "misapprehend", "misinterpret", "distort"]

[[synonyms]]
meaning = "预示、预兆 v."
words = ["presage", "portend", "adumbrate", "augur", "forebode", "herald", "betoken", "signify"]

[[synonyms]]
meaning = "聚集 v."
words = ["cluster", "collect", "aggregate", "assemble", "accumulate"]

[[synonyms]]
meaning = "（供应）过剩 n."
words = ["glut", "surfeit", "surplus", "excess", "plethora"]

[[synonyms]]
meaning = "短暂的、片刻的 adj."
words = ["momentary", "transient", "fleeting", "ephemeral", "evanescent", "transitory"]

[[synonyms]]
meaning = "划定界限 v."
words = ["demarcate", "delimit", "mark", "delineate"]

[[synonyms]]
meaning = "博学的 adj."
words = ["erudite", "polymath", "intelligent", "intellectual", "well-informed", "learned"]

[[synonyms]]
meaning = "尖叫 v."
words = ["shriek", "cry", "caterwaul", "scream", "yell", "screech", "roar"]

[[synonyms]]
meaning = "忽略 v."
words = ["overlook", "ignore", "neglect"]

[[synonyms]]
meaning = "奇异的、令人惊叹的 adj."
words = ["wondrous", "marvelous", "fantastic", "amazing", "wonderful", "astonishing"]

[[synonyms]]
meaning = "引起敌意 v."
words = ["irritate", "vex", "rile", "offend", "provoke", "antagonize"]

[[synonyms]]
meaning = "惊恐、焦虑不安 n."
words = ["trepidation", "misconcertment", "misgiving", "apprehension", "agitation", "unease"]

[[synonyms]]
meaning = "使慌乱不安 v."
words = ["unnerve", "fluster", "perturb", "disconcert", "disturb", "rattle"]

[[synonyms]]
meaning = "多用途的 adj."
words = ["versatile", "protean", "universal", "adaptable", "multifunctional"]

[[synonyms]]
meaning = "低下的、卑微的 adj."
words = ["unpretentious", "lowly", "humble", "modest", "unassuming"]

[[synonyms]]
meaning = "搁置、中止 n."
words = ["quiescence", "abeyance", "suspension", "moratorium", "doldrums", "adjournment"]




